In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [ ]:
cd /content/drive/MyDrive/AAE/AAE-PyTorch/data

/content/drive/MyDrive/AAE/AAE-PyTorch/data

In [ ]:
ls

describe_data         insdn_train_1%.npy   InSecLab2021.csv
insdn_test_1.npy      insdn_train_20%.npy  metasploitable-2.csv
insdn_test_2.npy      insdn_train_2%.npy   MNIST/
insdn_test.npy        insdn_train_50%.npy  Normal_data.csv
insdn_train_0.1%.npy  insdn_train_5%.npy   OVS.csv
insdn_train_10%.npy   insdn_train.npy      subMNIST/

In [ ]:
from sklearn import preprocessing

In [ ]:
df = pd.read_csv('Normal_data.csv')

In [ ]:
columns = ['Src Port', 'Dst Port', 'Protocol', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Bwd PSH Flags', 'Bwd URG Flags', 'Fwd Header Len',
       'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min',
       'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var',
       'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt',
       'ACK Flag Cnt', 'URG Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min']

In [ ]:
df = df[columns]

In [ ]:
scaler = preprocessing.MinMaxScaler()
df = scaler.fit_transform(df)

In [ ]:
df

array([[6.76201670e-03, 8.79504246e-01, 3.52941176e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [8.18921435e-01, 7.26253320e-03, 3.52941176e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.35893639e-01, 8.68880947e-04, 3.52941176e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [5.99651977e-01, 8.68880947e-04, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.61604567e-01, 8.68880947e-04, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.15714438e-01, 8.68880947e-04, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [ ]:
df4 = pd.read_csv('InSecLab2021.csv', index_col=0)

In [ ]:
df5 = df4

In [ ]:
df5.columns

Index(['Dst Port', 'Protocol', 'Flow Duration', 'Flow Byts/s', 'Flow Pkts/s',
       'Fwd Pkts/s', 'Bwd Pkts/s', 'Tot Fwd Pkts', 'Tot Bwd Pkts',
       'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Pkt Len Max', 'Pkt Len Min', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'Fwd Header Len', 'Bwd Header Len',
       'Fwd Seg Size Min', 'Fwd Act Data Pkts', 'Flow IAT Mean',
       'Flow IAT Max', 'Flow IAT Min', 'Flow IAT Std', 'Fwd IAT Tot',
       'Fwd IAT Max', 'Fwd IAT Min', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Bwd IAT Tot', 'Bwd IAT Max', 'Bwd IAT Min', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt',
       'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'ECE Flag Cnt',
       'Down/Up Ratio', 'Pkt Size Avg', 'Init Fwd Win Byts',
       'Init Bwd Win Byts', 'Active Max', 'Active Min', 'Active Mean',
       'Active Std', 'Idle Max', 'Idle Min', 'Idle Mean', 'Idle Std',
       'Fwd Byts/b Avg', 'Fwd Pkts/b Avg', 'Bwd Byts/b Avg', 'Bwd Pkts/b Avg',
       'Fwd Blk Rate Avg', 'Bwd Blk Rate Avg', 'Fwd Seg Size Avg',
       'Bwd Seg Size Avg', 'CWE Flag Count', 'Subflow Fwd Pkts',
       'Subflow Bwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Byts', 'Label'],
      dtype='object')

In [ ]:
del df1['Src IP']
del df1['Dst IP']
del df1['Src Port']
del df1['Timestamp']
del df1['Flow ID']

In [ ]:
df1.reindex(df5.columns, axis=1)

,Dst Port,Protocol,Flow Duration,Flow Byts/s,Flow Pkts/s,Fwd Pkts/s,Bwd Pkts/s,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,...,Fwd Blk Rate Avg,Bwd Blk Rate Avg,Fwd Seg Size Avg,Bwd Seg Size Avg,CWE Flag Count,Subflow Fwd Pkts,Subflow Bwd Pkts,Subflow Fwd Byts,Subflow Bwd Byts,Label
0,4444,6,269709,263.246684,33.369298,14.830799,18.538499,4,5,48,...,0,0,12.0,4.600000,0,4,5,48,23,U2R
1,4444,6,268599,85.629507,18.615110,7.446044,11.169066,2,3,0,...,0,0,0.0,7.666667,0,2,3,0,23,U2R
2,3632,6,22194,3739.749482,450.572227,225.286113,225.286113,5,5,53,...,0,0,10.6,6.000000,0,5,5,53,30,U2R
3,8180,6,9556,6278.777731,837.170364,418.585182,418.585182,4,4,30,...,0,0,7.5,7.500000,0,4,4,30,30,BFA
4,8180,6,8782,6832.156684,910.954225,455.477112,455.477112,4,4,30,...,0,0,7.5,7.500000,0,4,4,30,30,BFA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136738,4444,6,273133,84.208060,18.306100,7.322440,10.983660,2,3,0,...,0,0,0.0,7.666667,0,2,3,0,23,U2R
136739,4444,6,267969,600.815766,48.513074,22.390650,26.122425,6,7,138,...,0,0,23.0,3.285714,0,6,7,138,23,U2R
136740,139,6,1552555,77.291948,7.085095,3.864597,3.220498,6,5,60,...,0,0,10.0,12.000000,0,6,5,60,60,U2R
136741,4444,6,272141,84.515012,18.372829,7.349132,11.023697,2,3,0,...,0,0,0.0,7.666667,0,2,3,0,23,U2R
136742,4444,6,270361,484.537341,48.083858,22.192550,25.891308,6,7,108,...,0,0,18.0,3.285714,0,6,7,108,23,U2R

In [ ]:
df1 = pd.read_csv('metasploitable-2.csv')
df2 = pd.read_csv('Normal_data.csv')
df3 = pd.read_csv('OVS.csv')
df = pd.concat([df1, df2, df3], axis=0)
df = df.reset_index(drop=True)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.3.130-200.175.2.130-38694-4444-6,192.168.3.130,38694,200.175.2.130,4444,6,10/1/2020 5:02,269709,4,5,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,U2R
1,192.168.3.130-200.175.2.130-38693-4444-6,192.168.3.130,38693,200.175.2.130,4444,6,10/1/2020 5:02,268599,2,3,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,U2R
2,192.168.3.130-200.175.2.130-3632-33747-6,200.175.2.130,33747,192.168.3.130,3632,6,10/1/2020 5:02,22194,5,5,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,U2R
3,192.168.3.130-200.175.2.130-8180-38745-6,200.175.2.130,38745,192.168.3.130,8180,6,10/1/2020 1:39,9556,4,4,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BFA
4,192.168.3.130-200.175.2.130-8180-37217-6,200.175.2.130,37217,192.168.3.130,8180,6,10/1/2020 1:39,8782,4,4,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BFA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343884,172.17.0.2-200.175.2.130-80-55440-6,200.175.2.130,55440,172.17.0.2,80,6,25/12/2019 05:19:55 PM,296,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack
343885,172.17.0.2-200.175.2.130-80-55446-6,200.175.2.130,55446,172.17.0.2,80,6,25/12/2019 05:20:00 PM,3431,2,5,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack
343886,172.17.0.2-200.175.2.130-80-55446-6,200.175.2.130,55446,172.17.0.2,80,6,25/12/2019 05:20:00 PM,4121,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack
343887,172.17.0.2-200.175.2.130-80-55456-6,200.175.2.130,55456,172.17.0.2,80,6,25/12/2019 05:20:05 PM,5887,2,5,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack
343888,172.17.0.2-200.175.2.130-80-55456-6,200.175.2.130,55456,172.17.0.2,80,6,25/12/2019 05:20:05 PM,150,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack

<h1> Remove single value columns </h1>

In [ ]:
def distinct_val_of_columns(dataset):
    columns = dataset.columns
    num_val = []
    for column in columns:
        num_val.append(len(dataset[column].unique()))

    col_val_df = pd.DataFrame({'Column': columns, 'Distinct Value': num_val})
    single_val_cols = col_val_df[col_val_df['Distinct Value'] == 1]
    return col_val_df, single_val_cols

In [ ]:
col_val_df, single_val_cols = distinct_val_of_columns(df)

print(f"{len(single_val_cols)} single value columns")
print(single_val_cols['Column'].values)

12 single value columns
['Fwd PSH Flags' 'Fwd URG Flags' 'CWE Flag Count' 'ECE Flag Cnt'
 'Fwd Byts/b Avg' 'Fwd Pkts/b Avg' 'Fwd Blk Rate Avg' 'Bwd Byts/b Avg'
 'Bwd Pkts/b Avg' 'Bwd Blk Rate Avg' 'Init Fwd Win Byts'
 'Fwd Seg Size Min']

In [ ]:
dataset_preprocessing = df.drop(columns= single_val_cols['Column'].values)

In [ ]:
dataset_preprocessing

,Flow ID,Src IP,Src Port,Dst IP,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,...,Fwd Act Data Pkts,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,192.168.3.130-200.175.2.130-38694-4444-6,192.168.3.130,38694,200.175.2.130,4444,6,10/1/2020 5:02,269709,4,5,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,U2R
1,192.168.3.130-200.175.2.130-38693-4444-6,192.168.3.130,38693,200.175.2.130,4444,6,10/1/2020 5:02,268599,2,3,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,U2R
2,192.168.3.130-200.175.2.130-3632-33747-6,200.175.2.130,33747,192.168.3.130,3632,6,10/1/2020 5:02,22194,5,5,...,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,U2R
3,192.168.3.130-200.175.2.130-8180-38745-6,200.175.2.130,38745,192.168.3.130,8180,6,10/1/2020 1:39,9556,4,4,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BFA
4,192.168.3.130-200.175.2.130-8180-37217-6,200.175.2.130,37217,192.168.3.130,8180,6,10/1/2020 1:39,8782,4,4,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BFA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343884,172.17.0.2-200.175.2.130-80-55440-6,200.175.2.130,55440,172.17.0.2,80,6,25/12/2019 05:19:55 PM,296,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack
343885,172.17.0.2-200.175.2.130-80-55446-6,200.175.2.130,55446,172.17.0.2,80,6,25/12/2019 05:20:00 PM,3431,2,5,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack
343886,172.17.0.2-200.175.2.130-80-55446-6,200.175.2.130,55446,172.17.0.2,80,6,25/12/2019 05:20:00 PM,4121,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack
343887,172.17.0.2-200.175.2.130-80-55456-6,200.175.2.130,55456,172.17.0.2,80,6,25/12/2019 05:20:05 PM,5887,2,5,...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack
343888,172.17.0.2-200.175.2.130-80-55456-6,200.175.2.130,55456,172.17.0.2,80,6,25/12/2019 05:20:05 PM,150,1,1,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Web-Attack

<h1> Remove Non-Numeric Value Columns </h1>

In [ ]:
numberic_columns = list(dataset_preprocessing.select_dtypes(include=['int',"float"]).columns)

print(f" - Num. numberic columns: {len(numberic_columns)}")
print(f" - Numberic columns: {numberic_columns}")

 - Num. numberic columns: 67
 - Numberic columns: ['Src Port', 'Dst Port', 'Protocol', 'Flow Duration', 'Tot Fwd Pkts', 'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max', 'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std', 'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean', 'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min', 'Bwd PSH Flags', 'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg', 'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts', 'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Active Mean', 'Active Std', 'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min']

In [ ]:
non_numberic_columns = []
for column in dataset_preprocessing.columns:
    if column not in numberic_columns and column != 'Label':
        non_numberic_columns.append(column)

print(f" - Num. non-numberic columns: {len(non_numberic_columns)}")
print(f" - Non-numberic columns: {non_numberic_columns}")

 - Num. non-numberic columns: 4
 - Non-numberic columns: ['Flow ID', 'Src IP', 'Dst IP', 'Timestamp']

In [ ]:
# Drop non-numberic columns
dataset_preprocessing = dataset_preprocessing.drop(columns= non_numberic_columns)

In [ ]:
dataset_preprocessing.columns

Index(['Src Port', 'Dst Port', 'Protocol', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Bwd PSH Flags', 'Bwd URG Flags', 'Fwd Header Len',
       'Bwd Header Len', 'Fwd Pkts/s', 'Bwd Pkts/s', 'Pkt Len Min',
       'Pkt Len Max', 'Pkt Len Mean', 'Pkt Len Std', 'Pkt Len Var',
       'FIN Flag Cnt', 'SYN Flag Cnt', 'RST Flag Cnt', 'PSH Flag Cnt',
       'ACK Flag Cnt', 'URG Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Bwd Win Byts', 'Fwd Act Data Pkts', 'Active Mean', 'Active Std',
       'Active Max', 'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max',
       'Idle Min', 'Label'],
      dtype='object')

<h1> Label Encoder </h1>

In [ ]:
# enc1 = LabelEncoder()
# enc1.fit(df['proto'])
# df['proto'] = enc1.transform(df['proto'])

# # enc2 = LabelEncoder()
# # enc2.fit(df['service'])
# # df['service'] = enc2.transform(df['service'])

# # enc3 = LabelEncoder()
# # enc3.fit(df['state'])
# # df['state'] = enc3.transform(df['state'])

<h1> Remove unnecessary columns </h1>

In [ ]:
del df['Src Port']

<h1> Split dataset </h1>

In [ ]:
train, test = train_test_split(dataset_preprocessing, test_size=0.2)

In [ ]:
train_np = dataset_preprocessing.to_numpy()
np.save('ToN_IoT_train', train_np)

In [ ]:
test_np = dataset_preprocessing.to_numpy()
np.save('ToN_IoT_test', test_np)